# Generated by Django 3.0.2 on 2021-03-22 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_column='first_name', max_length=100, verbose_name='First Name')),
                ('lastname', models.CharField(db_column='last_name', max_length=100, verbose_name='Last Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('dob', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(db_column='project_name', max_length=100, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('projectLink', models.URLField(blank=True, db_column='project_link', null=True, verbose_name='Project Link')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('joinedYear', models.CharField(db_column='joined_year', max_length=4, verbose_name='company joined year')),
                ('leftYear', models.CharField(blank=True, db_column='left_year', max_length=4, null=True, verbose_name='company left year')),
                ('jobTitle', models.CharField(db_column='job_title', max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
            options={
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100, verbose_name='Course name (Ex. BSc.CSIT)')),
                ('university', models.CharField(blank=True, max_length=100, null=True, verbose_name='University')),
                ('joinedYear', models.CharField(db_column='joined_year', max_length=4)),
                ('passYear', models.CharField(blank=True, db_column='passed_year', max_length=4, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(db_column='skill_name', max_length=30, unique=True)),
                ('level', models.IntegerField(verbose_name='Level of Knowldege out of 100')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
            options={
                'db_table': 'skill',
                'unique_together': {('skillName', 'employee')},
            },
        ),
    ]
