# Generated by Django 3.0.2 on 2021-03-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skillName',
            field=models.CharField(db_column='skill_name', max_length=30),
        ),
    ]
